INSERT INTO ROLES (ROLE_NAME) VALUES('ROLE1');
INSERT INTO ROLES (ROLE_NAME) VALUES('ROLE2');
INSERT INTO ROLES (ROLE_NAME) VALUES('ROLE3');

INSERT INTO USERS (ID_ROLE, LOGIN, PASSWORD, EMAIL, CELL)
  VALUES(1, 'LOGIN1', 'PASSWORD1', 'EMAIL1', 'CELL1');
INSERT INTO USERS (ID_ROLE, LOGIN, PASSWORD, EMAIL, CELL)
  VALUES(2, 'LOGIN2', 'PASSWORD2', 'EMAIL2', 'CELL2');
INSERT INTO USERS (ID_ROLE, LOGIN, PASSWORD, EMAIL, CELL)
  VALUES(3, 'LOGIN3', 'PASSWORD3', 'EMAIL3', 'CELL3');

INSERT INTO CLIENT (ID_USER, FIRST_NAME, LAST_NAME)
  VALUES(1, 'CLIENT_FIRST_NAME1', 'CLIENT_LAST_NAME1');
INSERT INTO CLIENT (ID_USER, FIRST_NAME, LAST_NAME)
  VALUES(2, 'CLIENT_FIRST_NAME2', 'CLIENT_LAST_NAME2');
INSERT INTO CLIENT (ID_USER, FIRST_NAME, LAST_NAME)
  VALUES(3, 'CLIENT_FIRST_NAME3', 'CLIENT_LAST_NAME3');
