DROP TABLE ROLES IF EXISTS;
create memory table ROLES (
  ID_ROLE   INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY,
  ROLE_NAME VARCHAR(24) not null
);

DROP TABLE USERS IF EXISTS;
create memory table USERS (
  ID_USER INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY,
  ID_ROLE INTEGER not null,
  LOGIN   VARCHAR(24) not null,
  PASSWORD VARCHAR(128) not null,
  EMAIL   VARCHAR(48) not null,
  CELL    VARCHAR(16) not null
);

DROP TABLE CLIENT IF EXISTS;
create memory table CLIENT (
  ID_USER INTEGER PRIMARY KEY,
  FIRST_NAME VARCHAR(36) not null,
  LAST_NAME VARCHAR(36) not null
);

alter table USERS
add constraint FK_USERS_USER_ROLE_ROLE foreign key (ID_ROLE)
references ROLES (ID_ROLE)
  on delete restrict on update restrict;

alter table CLIENT
add constraint FK_CLIENT_RELATIONS_USERS foreign key (ID_USER)
references USERS (ID_USER)
  on delete restrict on update restrict;

ALTER TABLE users ADD CONSTRAINT uniquelogin UNIQUE (login);

ALTER TABLE users ADD CONSTRAINT uniqueemail UNIQUE (email);